image: Ubuntu 

stack: jdk 11 

branches:
  only:
    - main 

build: off  

install:
  - Java -jar app-ibank.jar -P:profile=test &
  - chmod +x gradlew

build_script:
  - ./gradlew test -Dselenide.headless=true --info
